language: scala

scala:
    - 2.12.1

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
sudo: required

jdk:
    - openjdk-8-jdk

branches:
    only:
        - master

notifications:
    email:
        - calin.cruceru@stud.acs.upb.ro

before_script:
    - sbt compile

script:
    - sbt test

    # Tricks to avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/
