language: scala

scala:
    - 2.12.1

jdk:
    - openjdk7

sudo: false

branches:
    only:
        - master

notifications:
    email:
        - calin.cruceru@stud.acs.upb.ro

before_script:
    - sbt compile

script:
    - sbt test

    # Tricks to avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/
