language: scala

scala:
    - 2.12.1

jdk:
    - oraclejdk8

sudo: false

branches:
    only:
        - master

notifications:
    email:
        - calin.cruceru@stud.acs.upb.ro

before_script:
    - sbt compile

script:
    - sbt clean coverage test

    # Tricks to avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
    - sbt coverageReport coveralls

cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/
